version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-petsocial
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=pet-social"
    networks:
      - node-network

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-petsocial
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - node-network

  es1:
    container_name: es1-petsocial
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      - cluster.name=${CLUSTER_NAME}
      - node.name=es1
      - cluster.initial_master_nodes=es1
      - discovery.seed_hosts=es1
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      # HTTPS
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=${CERTS_DIR}/es1/es1.key
      - xpack.security.http.ssl.certificate=${CERTS_DIR}/es1/es1.crt
      - xpack.security.http.ssl.certificate_authorities=${CERTS_DIR}/ca/ca.crt
      # SSL
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=${CERTS_DIR}/es1/es1.key
      - xpack.security.transport.ssl.certificate=${CERTS_DIR}/es1/es1.crt
      - xpack.security.transport.ssl.certificate_authorities=${CERTS_DIR}/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
    volumes:
      - es_data_1:/usr/share/elastic_search/data
      - ./elastic/certs:${CERTS_DIR}
    ports:
      - "9200:9200"
    healthcheck:
      test: curl --cacert elastic:Password http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - node-network

  kibana:
    depends_on:
      es1:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana_petsocial
    environment:
      - ELASTICSEARCH_HOSTS=["https://es1:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=F8gmlG5Pz2se3olQ5_aG
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/elastic/certs/ca/ca.crt
    volumes:
      - kibana_data:/usr/share/kibana/data
      - ./elastic/certs:/usr/share/kibana/config/elastic/certs
    ports:
      - "5601:5601"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - node-network

volumes:
  es_data_1:
    driver: local
  es_data_2:
    driver: local
  kibana_data:
    driver: local

networks:
  default:
    name: elastic
    external: false
  node-network:
    driver: bridge
