version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-petsocial
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=pet-social"
    networks:
      - node-network

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-petsocial
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
