# https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.reference.yml

metricbeat.modules:
#------------------------------- System Module -------------------------------
- module: system
  metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 10s
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: elasticsearch
  metricsets:
    - node
    - node_stats
    #- index
    #- index_recovery
    #- index_summary
    #- ingest_pipeline
    #- shard
    #- ml_job
  period: 10s
  hosts: ${ELASTICSEARCH_HOST}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
  ssl.certificate_authorities: [ "/etc/elastic/certs/ca/ca.crt" ]

  #index_recovery.active_only: true
  #ingest_pipeline.processor_sample_rate: 0.25
  #xpack.enabled: false
  #scope: node
#
#- module: system
#  period: 1m
#  metricsets:
#    - filesystem
#    - fsstat
#  processors:
#  - drop_event.when.regexp:
#      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
#
#- module: system
#  period: 15m
#  metricsets:
#    - uptime
#
##------------------------------- Docker Module -------------------------------
#- module: docker
#  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
#  hosts: ["unix:///var/run/docker.sock"]
#  period: 10s

#================================ Processors ===================================
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ${ELASTICSEARCH_HOST}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

  ssl.enabled: true
  ssl.verification_mode: certificate
  ssl.certificate_authorities: [ "/etc/elastic/certs/ca/ca.crt" ]
  ssl.certificate: "/etc/elastic/certs/es1/es1.crt"
  ssl.key: "/etc/elastic/certs/es1/es1.key"

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch: