// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: query.sql

package domain

import (
	"context"
)

const getPetById = `-- name: GetPetById :one
SELECT id, name, number FROM pets
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPetById(ctx context.Context, id string) (Pet, error) {
	row := q.db.QueryRowContext(ctx, getPetById, id)
	var i Pet
	err := row.Scan(&i.ID, &i.Name, &i.Number)
	return i, err
}
